### ISSUE TITLE
Support fastify v4

### ISSUE THREAD

**Issue by jambonn** [smartiniOnGitHub/fastify-favicon#11]
Fastify version: `"fastify": "^4.0.0"`

Command error
`"type":"Error","msg":"fastify-plugin: fastify-favicon - expected '3.x' fastify version, '4.0.0' is installed"}`

Please update the plugin to support Fastify 4. Thank!

**Comment by smartiniOnGitHub** [comment]
Sure, I'll do ASAP ...

**Comment by smartiniOnGitHub** [comment]
Hi, just published plugin 4.0.0, for Fastify 4.x (and so Node.js 14 LTS), hope all is good ... Bye
