### ISSUE TITLE
Error when using with Node.js v18.13.0

### ISSUE THREAD

**Issue by Josue715m** [smartiniOnGitHub/fastify-favicon#14]
Greetings,

When using the latest version of fastify-favicon:"V4.2.0" along with "fastify": "4.12.0" and Node.js v18.13.0 I get this error:

xxxx/yyyy/node_modules/fastify-favicon/src/plugin.js:1
Error: Cannot find module 'node:path'

code: 'MODULE_NOT_FOUND',

I have been trying to edit plugin.js to make it work with no success.

Do yoy know what is causing this error and how to fix it?

Thanks

**Comment by smartiniOnGitHub** [comment]
Hi, didn't tried (yet) with Node.js 18 LTS, sorry; I'll do ASAP and tell you something. Bye

**Comment by smartiniOnGitHub** [comment]
Hi @Josue715m I just tried from inside the plugin but all seems good to me: its tests and its example run fine even with Node.js 18 LTS; I'll try ASAP in a test application.
Note: I just started to draft a new release (4.3.0) with updated dependencies and improved compatibility with TypeScript 4.9.x and NodeNext / ESNext; all seems fine even here; anyway if I find some problem I'll add fixes here so soon I could publish a release ... could you try using this code (already pushed to master) ?
Thanks. Bye

**Comment by smartiniOnGitHub** [comment]
Update: with Node.js 18.13.0 current (4.2.0) version of the plugin seems to work, for example in my example [fastify-example-ts](https://github.com/smartiniOnGitHub/fastify-example-ts/); even the draft for next (4.3.0) release.
In some tests I forgot to perform a build of TS code, but after doing it everything is working fine.
Do you have a public repo or some test code so I can reproduce ? Thanks. Bye

**Comment by Josue715m** [comment]
Hi @smartiniOnGitHub, thank you for your quick answer. I don´t have a public repo, I'm migrating from Express+Marko.js to Fastify+Marko.js, still a lot of things to do.  App starts fine without favicon, once I add favicon I get the: Error: Cannot find module 'node:path'.

Would try using your update, maybe there is something wrong on my end.  Will update if I figure out what is causing this error.

Thanks

**Comment by smartiniOnGitHub** [comment]
ok; just for info, note that the `node:` import is supported in Node.js v16.0.0+ , v14.18.0+ , 18.0.0+, see https://nodejs.org/api/esm.html#node-imports . Ensure to have the right version (for example with `node --version`) because if you have multiple versions (maybe installed with `nvm`) in VSCode only default version is used in terminals, unless you change the current version. Tell me something. Bye

**Comment by smartiniOnGitHub** [comment]
Hi @Josue715m some update ? Otherwise I think I can drop the issue ...

**Comment by Josue715m** [comment]
Hi, yes please do. I haven´t been able to identify the problem,  It could be something on my side.   I will get back in case I find out the issue, for now please close this one.
Thanks
