### ISSUE TITLE
Serving default favicon only when no favicon found in project source.

### ISSUE THREAD

**Issue by fralonra** [smartiniOnGitHub/fastify-favicon#2]
This package serves favicon from `node_modules/fastify-favicon`. But in most cases, developers don't put favicon there.

I think it's better to follow these steps:
1. Find favicon in path which set in plugin options. (TODO)
2. Find favicon in project root.
3. Find favicon in `node_modules/fastify-favicon`.

That is, using package provided icon only when no icon found in project source.

**Comment by smartiniOnGitHub** [comment]
Thanks for the contribution, I'll take a look soon and provide feedback, thanks for now.
